### ISSUE TITLE
Using "nonstandard" priors: What is the needed fileformat?

### ISSUE THREAD

**Issue by jakgel** [EliseJ/astroABC#5]
Dear Elise,
 I was going to use astroABC with a multivariate Gaussian in two dimensions and a flat prior in another one.

While I can create a pdf with scipy I have issues converting it into the needed fileformat to use as an
 "nonstandard"  prior.

For the  future it would be great to link to an example of an usable set of files like
"Planck/WMAP chain".

Also that the number of files to read and the filepath is hard-coded makes it a little bit harder to come up with a general solution.

Thanks

**Comment by EliseJ** [comment]
Hi Jakob,

Thanks for you question and sorry this part is not documented correctly! I agree that having file name and number as a global setting is not great. If I get time I will re-write this so it can be passed as a command line option.
Also using a multiGaussian is a "standard pdf" whereas the nonstandard option was intended for sampling from a non-analytical pdf like one you might get from MCMC sampling.
Unfortunately though I haven't coded up an option for two parameters to share a joint pdf as a prior.

A very quick fix to this would be to add to priors.py as

    def return_priorprob(self,value):
         .....
         elif self.priorname == "multigauss":

              mean1=self.hyperparams[0]
              mean2=self.hyperparams[1]
              COV=self.hyperparams[2]
              return scipy.stats.multivariate_normal.pdf(x, mean=[mean1,mean2], cov=COV))

and 

    def prior(self):
        ......
        elif self.priorname == "multigauss":
            mean1=self.hyperparams[0]
            mean2=self.hyperparams[1]
            COV=self.hyperparams[2]
            return scipy.stats.multivariate_normal.rvs(mean=[mean1,mean2], cov=COV)

Then  priors =  [('multigauss', [mean1,mean2,COV]) where mean 1 and 2 are the means of the 2D MultiGaussian and COV is a 4x4 covariance matrix.
This solution is not great though as there will be two calls to these functions for parameter 1 and 2 which is redundant and might slow down the sampler.

For the non-standard option the format expected is from a single pdf for one parameter written as text column output. Let's say you have the output from an MCMC run, each column in the output file would then correspond to the marginalized 1D pdf for each of the parameters. E.g. for parameter A whose pdf is in column 0 in "output_1.txt"  use:

`NFILES = 1`
`FILENAME = "output_"  `

and prior setting priors =  [('nonstandard', [0])

For your example with a multiGaussian in 2D and uniform in 1D one possible solution would be to find the 1D marginalized pdfs for the first two parameters and save them as column 0,1 in a file.
For the 3rd parameter you can use priors =  [('uniform', [value_1,value_2]).

**Comment by jakgel** [comment]
Thanks,
 I think the fix to the priors.py to be appropriate, as the evaluation of the sampler only takes an negligible amount of time compared to the generation of models in my case.

**Comment by EliseJ** [comment]
Great, thanks Jakob. If you have a version which you think would be useful to others, feel free to issue a PR.
